feat: add start & login fragment for android
sgdevcamp2023/palette pull request #26
Opened 2024-01-11 08:35 UTC by HeewonP825

## Related Issue

#25 

## Changes

### 작업 사항
- `theme`, `string` 세팅
- navigation 폴더의 `nav_graph` 파일에 `loginFragment`, `startFragment`, `PasswordFragment` 경로 설정
- `nav_graph`에서 `action`을 사용해서 fragment간 이동 설정
- `fragment_login`, `fragment_start`, `fragment_password`에서 `.xml`ui 디자인 완료

## Screenshots

## To Reviewer

## Additional Context(optional)

## How Has This Been Tested?

## Checklist

- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가
- [x] PR에 대해 구체적으로 설명이 되어있는가

2024-01-11 23:36 UTC, poiu694 requested changes
리뷰 남겼습니당~

2024-01-11 23:36 UTC, poiu694 commented on src/mobile/app/src/main/java/com/smilegate/Easel/ui/login/PasswordFragment.kt
> +}
```suggestion
}

```

eol 부탁드립니다~

2024-01-11 23:36 UTC, poiu694 commented on src/mobile/app/src/main/res/drawable/btn_login_fragment_next.xml
> +</shape>
```suggestion

```

eol !

2024-01-11 23:36 UTC, poiu694 commented on src/mobile/app/src/main/res/values/strings.xml
> +    <string name="start_fragment_headline">지금 세계에서 무슨 일이 일어\n나고 있는지 알아보세요.</string>
여기 부분이랑 아래 부분에서 개행을 강제하는게 나을까요? 뷰포트에 대응이 잘 되는지가 궁금해요!

2024-01-12 00:46 UTC, HeewonP825 commented on src/mobile/app/src/main/res/values/strings.xml
> +    <string name="start_fragment_headline">지금 세계에서 무슨 일이 일어\n나고 있는지 알아보세요.</string>
`android:breakStrategy="balanced"` 속성을 텍스트뷰에 적용하면 가능하긴한데 그러면 margin값이 무시되는것 같아서 어려울 것 같습니다....ㅠ 일단 개행문자로 하는게 최선일 것 같고 다른 방법이 있나 틈틈히 찾아볼게용

2024-01-12 00:46 UTC, HeewonP825 commented on src/mobile/app/src/main/res/drawable/btn_login_fragment_next.xml
> +</shape>
추가했어요..ㅎㅎㅎㅎ

2024-01-12 00:46 UTC, HeewonP825 commented on src/mobile/app/src/main/java/com/smilegate/Easel/ui/login/PasswordFragment.kt
> +}
추가했습니닿ㅎ

2024-01-12 00:58 UTC, poiu694 commented on src/mobile/app/src/main/res/values/strings.xml
> +    <string name="start_fragment_headline">지금 세계에서 무슨 일이 일어\n나고 있는지 알아보세요.</string>
확인했습니다 :)

2024-01-12 01:01 UTC, poiu694 approved these changes
죠습니당 :fire::fire:

2024-01-12 01:01 UTC, merged